export const prerender = true;

export async function GET() {
  const en = [
    { title: 'Welcome to Quira', path: '/docs/en/', section: 'Getting Started', lang: 'en', keywords: ['welcome', 'introduction', 'overview', 'browser', 'context graph'] },
    { title: 'What is Quira?', path: '/docs/en/getting-started/what-is-quira/', section: 'Getting Started', lang: 'en', keywords: ['what', 'quira', 'browser', 'context', 'local-first', 'AI'] },
    { title: 'Quick Start', path: '/docs/en/getting-started/quick-start/', section: 'Getting Started', lang: 'en', keywords: ['quick start', 'install', 'setup', 'begin', 'download'] },
    { title: 'Installation', path: '/docs/en/getting-started/installation/', section: 'Getting Started', lang: 'en', keywords: ['install', 'macos', 'linux', 'build', 'source', 'requirements'] },
    { title: 'Context Graph', path: '/docs/en/core-concepts/context-graph/', section: 'Core Concepts', lang: 'en', keywords: ['context graph', 'knowledge graph', 'nodes', 'edges', 'browsing', 'visualization'] },
    { title: 'Context Spaces', path: '/docs/en/core-concepts/context-spaces/', section: 'Core Concepts', lang: 'en', keywords: ['spaces', 'tabs', 'workspaces', 'organize', 'GTD', 'inbox'] },
    { title: 'Local AI', path: '/docs/en/core-concepts/local-ai/', section: 'Core Concepts', lang: 'en', keywords: ['AI', 'local', 'LLM', 'phi', 'llama', 'privacy', 'on-device'] },
    { title: 'Research Replay', path: '/docs/en/core-concepts/research-replay/', section: 'Core Concepts', lang: 'en', keywords: ['research', 'replay', 'resume', 'session', 'continue'] },
    { title: 'Natural Language Query', path: '/docs/en/features/nl-query/', section: 'Features', lang: 'en', keywords: ['query', 'search', 'ask', 'natural language', 'command palette', 'NL'] },
    { title: 'AI Privacy Levels', path: '/docs/en/features/ai-privacy/', section: 'Features', lang: 'en', keywords: ['privacy', 'AI', 'local', 'cloud', 'shield', 'data'] },
    { title: 'Graph Visualization', path: '/docs/en/features/graph-visualization/', section: 'Features', lang: 'en', keywords: ['visualization', 'graph', 'WebGPU', 'render', 'filter', 'timeline'] },
    { title: 'Export & Import', path: '/docs/en/features/export-import/', section: 'Features', lang: 'en', keywords: ['export', 'import', 'JSON', 'markdown', 'chrome', 'data'] },
    { title: 'Technical Overview', path: '/docs/en/architecture/technical-overview/', section: 'Architecture', lang: 'en', keywords: ['architecture', 'layers', 'UI', 'context', 'agent', 'gecko'] },
    { title: 'Gecko Engine', path: '/docs/en/architecture/gecko-engine/', section: 'Architecture', lang: 'en', keywords: ['gecko', 'firefox', 'engine', 'servo', 'fork', 'zen'] },
    { title: 'Storage (SQLite)', path: '/docs/en/architecture/storage/', section: 'Architecture', lang: 'en', keywords: ['storage', 'sqlite', 'database', 'FTS5', 'vector', 'schema'] },
    { title: 'LLM Integration', path: '/docs/en/architecture/llm-integration/', section: 'Architecture', lang: 'en', keywords: ['LLM', 'llama', 'MLX', 'RAG', 'inference', 'model'] },
    { title: 'Development Setup', path: '/docs/en/contributing/dev-setup/', section: 'Contributing', lang: 'en', keywords: ['development', 'setup', 'build', 'rust', 'node', 'just'] },
    { title: 'Code Style', path: '/docs/en/contributing/code-style/', section: 'Contributing', lang: 'en', keywords: ['code', 'style', 'rust', 'typescript', 'lint', 'format'] },
    { title: 'Pull Requests', path: '/docs/en/contributing/pull-requests/', section: 'Contributing', lang: 'en', keywords: ['pull request', 'PR', 'review', 'merge', 'branch'] },
    { title: 'RFC Process', path: '/docs/en/contributing/rfc-process/', section: 'Contributing', lang: 'en', keywords: ['RFC', 'proposal', 'discussion', 'change', 'process'] },
    { title: 'Plugin API', path: '/docs/en/api/plugin-api/', section: 'API Reference', lang: 'en', keywords: ['plugin', 'API', 'extension', 'manifest', 'permissions'] },
    { title: 'WebExtension API', path: '/docs/en/api/webextension-api/', section: 'API Reference', lang: 'en', keywords: ['webextension', 'MV2', 'MV3', 'firefox', 'compatibility'] },
    { title: 'Graph Query API', path: '/docs/en/api/graph-query-api/', section: 'API Reference', lang: 'en', keywords: ['graph', 'query', 'API', 'search', 'nodes', 'related'] },
    { title: 'Security Overview', path: '/docs/en/security/overview/', section: 'Security & Privacy', lang: 'en', keywords: ['security', 'overview', 'privacy', 'protection', 'threat model'] },
    { title: 'Network Firewall', path: '/docs/en/security/network-firewall/', section: 'Security & Privacy', lang: 'en', keywords: ['network', 'firewall', 'filter', 'DNS', 'tracking', 'block'] },
    { title: 'Privacy Architecture', path: '/docs/en/security/privacy-architecture/', section: 'Security & Privacy', lang: 'en', keywords: ['privacy', 'architecture', 'local-first', 'data', 'encryption'] },
    { title: 'Content Filtering', path: '/docs/en/security/content-filtering/', section: 'Security & Privacy', lang: 'en', keywords: ['content', 'filtering', 'ads', 'tracker', 'block'] },
    { title: 'Threat Protection', path: '/docs/en/security/threat-protection/', section: 'Security & Privacy', lang: 'en', keywords: ['threat', 'protection', 'malware', 'phishing', 'safe browsing'] },
    { title: 'Permission System', path: '/docs/en/security/permission-system/', section: 'Security & Privacy', lang: 'en', keywords: ['permission', 'system', 'access', 'control', 'sandbox'] },
    { title: 'For Developers', path: '/docs/en/use-cases/developers/', section: 'Use Cases', lang: 'en', keywords: ['developer', 'research', 'API', 'code review', 'Stack Overflow', 'GitHub', 'workflow'] },
    { title: 'For Researchers', path: '/docs/en/use-cases/researchers/', section: 'Use Cases', lang: 'en', keywords: ['researcher', 'literature', 'review', 'citation', 'paper', 'academic', 'PubMed', 'arXiv'] },
    { title: 'For Writers', path: '/docs/en/use-cases/writers/', section: 'Use Cases', lang: 'en', keywords: ['writer', 'content', 'creator', 'article', 'blog', 'fact-check', 'source', 'research'] },
    { title: 'Troubleshooting', path: '/docs/en/troubleshooting/', section: 'Resources', lang: 'en', keywords: ['troubleshooting', 'FAQ', 'error', 'fix', 'problem', 'install', 'performance', 'build'] },
    { title: 'Release Notes', path: '/docs/en/release-notes/', section: 'Resources', lang: 'en', keywords: ['release', 'notes', 'changelog', 'version', 'update', 'alpha', 'beta', 'breaking'] },
  ];
  const ja = [
    { title: 'Quira へようこそ', path: '/docs/ja/', section: 'はじめに', lang: 'ja', keywords: ['ようこそ', '概要', 'ブラウザ', 'コンテキストグラフ', 'welcome'] },
    { title: 'Quira とは？', path: '/docs/ja/getting-started/what-is-quira/', section: 'はじめに', lang: 'ja', keywords: ['quira', 'ブラウザ', 'コンテキスト', 'ローカルファースト', 'AI'] },
    { title: 'クイックスタート', path: '/docs/ja/getting-started/quick-start/', section: 'はじめに', lang: 'ja', keywords: ['クイックスタート', 'インストール', '設定', 'ダウンロード'] },
    { title: 'インストール', path: '/docs/ja/getting-started/installation/', section: 'はじめに', lang: 'ja', keywords: ['インストール', 'macos', 'linux', 'ビルド', '要件'] },
    { title: 'Context Graph', path: '/docs/ja/core-concepts/context-graph/', section: 'コアコンセプト', lang: 'ja', keywords: ['コンテキストグラフ', 'ナレッジグラフ', 'ノード', 'エッジ', '可視化'] },
    { title: 'Context Spaces', path: '/docs/ja/core-concepts/context-spaces/', section: 'コアコンセプト', lang: 'ja', keywords: ['スペース', 'タブ', 'ワークスペース', '整理', 'GTD'] },
    { title: 'ローカル AI', path: '/docs/ja/core-concepts/local-ai/', section: 'コアコンセプト', lang: 'ja', keywords: ['AI', 'ローカル', 'LLM', 'phi', 'プライバシー'] },
    { title: 'Research Replay', path: '/docs/ja/core-concepts/research-replay/', section: 'コアコンセプト', lang: 'ja', keywords: ['リサーチ', 'リプレイ', '再開', 'セッション'] },
    { title: '自然言語クエリ', path: '/docs/ja/features/nl-query/', section: '機能', lang: 'ja', keywords: ['クエリ', '検索', '自然言語', 'コマンドパレット'] },
    { title: 'AI プライバシーレベル', path: '/docs/ja/features/ai-privacy/', section: '機能', lang: 'ja', keywords: ['プライバシー', 'AI', 'ローカル', 'クラウド', 'シールド'] },
    { title: 'グラフ可視化', path: '/docs/ja/features/graph-visualization/', section: '機能', lang: 'ja', keywords: ['可視化', 'グラフ', 'WebGPU', 'レンダリング', 'フィルター'] },
    { title: 'エクスポート & インポート', path: '/docs/ja/features/export-import/', section: '機能', lang: 'ja', keywords: ['エクスポート', 'インポート', 'JSON', 'マークダウン', 'データ'] },
    { title: '技術概要', path: '/docs/ja/architecture/technical-overview/', section: 'アーキテクチャ', lang: 'ja', keywords: ['アーキテクチャ', 'レイヤー', 'UI', 'gecko'] },
    { title: 'Gecko エンジン', path: '/docs/ja/architecture/gecko-engine/', section: 'アーキテクチャ', lang: 'ja', keywords: ['gecko', 'firefox', 'エンジン', 'servo'] },
    { title: 'ストレージ (SQLite)', path: '/docs/ja/architecture/storage/', section: 'アーキテクチャ', lang: 'ja', keywords: ['ストレージ', 'sqlite', 'データベース', 'FTS5', 'ベクトル'] },
    { title: 'LLM 統合', path: '/docs/ja/architecture/llm-integration/', section: 'アーキテクチャ', lang: 'ja', keywords: ['LLM', 'llama', 'MLX', 'RAG', '推論'] },
    { title: '開発環境セットアップ', path: '/docs/ja/contributing/dev-setup/', section: 'コントリビュート', lang: 'ja', keywords: ['開発', 'セットアップ', 'ビルド', 'rust', 'node'] },
    { title: 'コードスタイル', path: '/docs/ja/contributing/code-style/', section: 'コントリビュート', lang: 'ja', keywords: ['コード', 'スタイル', 'rust', 'typescript', 'lint'] },
    { title: 'プルリクエスト', path: '/docs/ja/contributing/pull-requests/', section: 'コントリビュート', lang: 'ja', keywords: ['プルリクエスト', 'PR', 'レビュー', 'マージ'] },
    { title: 'RFC プロセス', path: '/docs/ja/contributing/rfc-process/', section: 'コントリビュート', lang: 'ja', keywords: ['RFC', '提案', 'ディスカッション', 'プロセス'] },
    { title: 'Plugin API', path: '/docs/ja/api/plugin-api/', section: 'API リファレンス', lang: 'ja', keywords: ['プラグイン', 'API', '拡張', 'マニフェスト'] },
    { title: 'WebExtension API', path: '/docs/ja/api/webextension-api/', section: 'API リファレンス', lang: 'ja', keywords: ['webextension', 'MV2', 'MV3', 'firefox', '互換性'] },
    { title: 'Graph Query API', path: '/docs/ja/api/graph-query-api/', section: 'API リファレンス', lang: 'ja', keywords: ['グラフ', 'クエリ', 'API', '検索', 'ノード'] },
    { title: 'セキュリティ概要', path: '/docs/ja/security/overview/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['セキュリティ', '概要', 'プライバシー', '保護'] },
    { title: 'ネットワークファイアウォール', path: '/docs/ja/security/network-firewall/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['ネットワーク', 'ファイアウォール', 'フィルター', 'DNS', 'トラッキング'] },
    { title: 'プライバシーアーキテクチャ', path: '/docs/ja/security/privacy-architecture/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['プライバシー', 'アーキテクチャ', 'ローカルファースト', '暗号化'] },
    { title: 'コンテンツフィルタリング', path: '/docs/ja/security/content-filtering/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['コンテンツ', 'フィルタリング', '広告', 'トラッカー', 'ブロック'] },
    { title: '脅威対策', path: '/docs/ja/security/threat-protection/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['脅威', '対策', 'マルウェア', 'フィッシング', 'セーフブラウジング'] },
    { title: 'パーミッションシステム', path: '/docs/ja/security/permission-system/', section: 'セキュリティ & プライバシー', lang: 'ja', keywords: ['パーミッション', 'システム', 'アクセス', '制御', 'サンドボックス'] },
    { title: '開発者向け', path: '/docs/ja/use-cases/developers/', section: 'ユースケース', lang: 'ja', keywords: ['開発者', 'リサーチ', 'API', 'コードレビュー', 'ワークフロー'] },
    { title: '研究者向け', path: '/docs/ja/use-cases/researchers/', section: 'ユースケース', lang: 'ja', keywords: ['研究者', '文献', 'レビュー', '引用', '論文', '学術'] },
    { title: 'ライター向け', path: '/docs/ja/use-cases/writers/', section: 'ユースケース', lang: 'ja', keywords: ['ライター', 'コンテンツ', 'クリエイター', '記事', 'ブログ', 'ファクトチェック'] },
    { title: 'トラブルシューティング', path: '/docs/ja/troubleshooting/', section: 'リソース', lang: 'ja', keywords: ['トラブルシューティング', 'FAQ', 'エラー', '修正', '問題', 'インストール', 'パフォーマンス'] },
    { title: 'リリースノート', path: '/docs/ja/release-notes/', section: 'リソース', lang: 'ja', keywords: ['リリース', 'ノート', '変更履歴', 'バージョン', 'アップデート', 'アルファ'] },
  ];
  return new Response(JSON.stringify([...en, ...ja]), {
    headers: { 'Content-Type': 'application/json' }
  });
}
